name: RailsBridge LA
markdown: redcarpet
pygments: true
baseurl: /rbla

vimeo: vimeo.com
youtube: youtube.com

permalink: /:categories/:title
permalink: /blog/:year/:month/:day/:title

categories: "tutorials", "cheatsheets", "blog"

tags: ["Git"]