name: RailsBridge LA
markdown: redcarpet
pygments: true
baseurl: /rbla

vimeo: vimeo.com
youtube: youtube.com

# permalink: /blog/:categories/:title
permalink: /blog/:year/:month/:day/:title 

categories: 
  - tutorials
  - cheatsheets
  - core basics

tags: ["Git"]

gems: ['jekyll/itafroma/archive']

archive:
  layout: archive
  path: /blog/
  title: Blog Archive 
  
paginate: 5
paginate_path: "blog/page:num"