name: RailsBridge LA
markdown: redcarpet
pygments: true
baseurl: /rbla
category_dir: /categories
url: http://localhost:4000/

vimeo: vimeo.com
youtube: youtube.com

# permalink: /blog/:categories/:title 
permalink: /blog/:year/:month/:day/:title     

categories: 
  - tutorials
  - cheatsheets
  - core-basics

tags: ["Git"]

gems: ['jekyll/itafroma/archive']

archive:
  layout: archive
  path: /blog/
  title: Blog Archive 
  
paginate: 1
paginate_path: "page/page:num"      